### ISSUE TITLE
[BUG] Не загружается информация

### ISSUE THREAD

**Issue by nikotrue** [Jenstel/Kinopoisk.bundle#22]
Не подгружает изображения, описания и прочую информацию. В логах вижу, что данные от api получаю. Ошибка из лога ниже.

**Шаги для вопроизведения ошибки**
1. Перехожу в фильм kp-1367856
2. "Исправление сопоставления"
3. "Обновить метаданные"

**Ожидание**
Загрузка информации

2022-02-07 22:37:25,658 (4908) :  ERROR (logkit:22) - local variable 'series_resp' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\Niko\AppData\Local\Plex Media Server\Plug-ins\Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\utils.py", line 228, in update_event
    self.fire('update', metadict, media, lang, force, periodic)
  File "C:\Users\Niko\AppData\Local\Plex Media Server\Plug-ins\Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\agent.py", line 15, in fire
    [getattr(s, event)(*args, **kwargs) for s in self.sources]
  File "C:\Users\Niko\AppData\Local\Plex Media Server\Plug-ins\Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\sources\tvdb.py", line 50, in update
    if 'errors' in series_resp and series_resp['errors'].get('invalidLanguage') and lang != 'en':
UnboundLocalError: local variable 'series_resp' referenced before assignment

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Windows
 - Браузер Firefox
 - Версия PLEX 4.69.1 
 - Имя сервера HOME_5900
 - Версия агента кинопоиск 3.0.3

**Дополнительная информация**
Если необходимы полные логи - могу так же предоставить.

**Comment by nikotrue** [comment]
Вынес `series_resp = self.make_request(self.conf.series, lang, source_id)` на уровень выше - помогло!
