### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eds-ch** [Jenstel/Kinopoisk.bundle#27]
**Описание ошибки**
Не подгружаются данные с Кинопоиска. Сами фильмы находятся, правильно находит название и год. 

**Шаги для вопроизведения ошибки**
1. Перейти в библиотеку с фильмами
2. Нажать сопоставить
3. Выбрать фильм
4. Сопоставление происходит, картинки не подгружаются

**Ожидание**
Должны загружаться данные с кинопоиска. С других баз данных все загружается.

**Характеристики сервера PLEX и версия агента КиноПоиск:**
 - OS: Synology (пробовал в Docker, результат такой же)
 - Браузер - FireFox
 - Версия PLEX 1.32.1.6999
 - Имя сервера ds1520
 - Версия агента кинопоиск 663f5d8

**Дополнительная информация**
Ключ для доступа к API прописан. Он же настроен у меня в Jellyfin и там все корректно работает.

**Comment by luxerus** [comment]
Аналогичная проблема, появилась 2-3 месяца назад. Вдруг перестали загружаться метаданные через этот плагин. Станция Synology DS415play.

**Comment by garm-su** [comment]
Аналогичная проблема

**Comment by GoodwinSan** [comment]
та же проблема

**Comment by andreykhr** [comment]
Тоже самое

**Comment by xes66** [comment]
Тоже не работает. Плагин стоит на Plex сервере на Ubuntu

**Comment by Distraekt** [comment]
аналогичная проблема. Данные через этот плагин не подгружаются. Плекс на Synology DS718+

**Comment by OlegTretyakov** [comment]
Присоединяюсь. Перестал работать. И поле для ключа kinopoiskapiunofficial.tech пропало. И в каналах обновления нет Jenstel, amirotin. Переименовать старую директорию и заново поставить в новую, с любого репозитория через git clone https://github.com/Jenstel/Kinopoisk.bundle.git - пробовал. Plex новую директорию удаляет. Сервер - Ubuntu

![image](https://github.com/Jenstel/Kinopoisk.bundle/assets/24296157/668c68c2-69ce-4bd7-8fee-1febedb75f96)
![image](https://github.com/Jenstel/Kinopoisk.bundle/assets/24296157/6e454cdb-d7e4-4dd8-8ee1-4fa46f59e0c2)
![image](https://github.com/Jenstel/Kinopoisk.bundle/assets/24296157/69c6e033-83fe-454f-9a19-05207547fb0e)

**Comment by kurakinvit** [comment]
У меня такая же проблема -  с других баз данных постеры и описания загружаются, а с Кинопоиска нет.
@OlegTretyakov 
В последнем посте пункт 3 - скачать заново.
Что нужно скачать заново?

**Comment by OlegTretyakov** [comment]
> У меня такая же проблема - с других баз данных постеры и описания загружаются, а с Кинопоиска нет. 
> @OlegTretyakov В последнем посте пункт 3 - скачать заново. Что нужно скачать заново?

@kurakinvit ,имелось ввиду пройти процесс скачивания и установки плагина заново
git clone https://github.com/Jenstel/Kinopoisk.bundle.git
и далее.
Сериалы этот плагин и у меня не подтягивал. Похоже ни у кого.

**Comment by kurakinvit** [comment]
> Сериалы этот плагин и у меня не подтягивал. Похоже ни у кого.

У меня 2 недели назад нормально подтягивал сериалы.

**Comment by ilyvasile** [comment]
Помогло полное отключение загрузки трейлеров + отзывов в плагине, на основе подобных ошибок в логах
C:\Users\%USERNAME%\AppData\Local\Plex Media Server\Logs\PMS Plugin Logs\com.plexapp.agents.kinopoisk2.log

> 2023-07-18 23:39:43,015 (1a5c) :  DEBUG (utils:111) - Requesting 'https://widgets.kinopoisk.ru/discovery/api/trailers?params=762646%2C186464%2Crnd-0.578699428634%3B762646%2C187139%2Crnd-0.303690504613%3B762646%2C187974%2Crnd-0.954311086783%3B762646%2C187503%2Crnd-0.554467434058%3B762646%2C188530%2Crnd-0.318890936223%3B762646%2C188531%2Crnd-0.435625026296%3B762646%2C183451%2Crnd-0.183674233057%3B762646%2C187167%2Crnd-0.256585315275'
2023-07-18 23:39:43,835 (1a5c) :  WARNING (data:179) - Error decoding with simplejson, using demjson instead (this will cause a performance hit) - Expecting value: line 1 column 1 (char 0)
2023-07-18 23:39:43,835 (1a5c) :  ERROR (logkit:22) - Something goes wrong with request
Traceback (most recent call last):
  File "C:\Users\ilyva\AppData\Local\Plex Media Server\Plug-ins\Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\sources\base.py", line 30, in _fetch
    data = getattr(self.api, obj_type).ObjectFromString(req.content)
  File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-7c8f9d3b6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\parsekit.py", line 97, in ObjectFromString
    return self._core.data.json.from_string(string, encoding)
  File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-7c8f9d3b6\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\data.py", line 180, in from_string
    return demjson.decode(jsonstring, encoding)
  File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-7c8f9d3b6\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\demjson.py", line 2058, in decode
    unitxt = auto_unicode_decode( txt )
  File "C:\Program Files\Plex\Plex Media Server\Resources\Plug-ins-7c8f9d3b6\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\demjson.py", line 679, in auto_unicode_decode
    unis = s.decode(encoding)
  File "C:\Program Files\Plex\Plex Media Server\python27.zip\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 0: invalid start byte
2023-07-18 23:39:43,835 (1a5c) :  ERROR (logkit:22) - 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\ilyva\AppData\Local\Plex Media Server\Plug-ins\Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\utils.py", line 228, in update_event
    self.fire('update', metadict, media, lang, force, periodic)
  File "C:\Users\ilyva\AppData\Local\Plex Media Server\Plug-ins\Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\agent.py", line 15, in fire
    [getattr(s, event)(*args, **kwargs) for s in self.sources]
  File "C:\Users\ilyva\AppData\Local\Plex Media Server\Plug-ins\Kinopoisk.bundle\Contents\Libraries\Shared\kinoplex\sources\kptrailers.py", line 173, in update
    headers=self.conf.extras.headers()
TypeError: 'NoneType' object is not iterable

**Comment by kurakinvit** [comment]
> Помогло полное отключение загрузки трейлеров

Этот момент я выяснил читая форумы еще 1.5 года назад и с тех пор загрузка трейлеров отключена.
Но настораживает то, что по фильмам отлично ищет, а по сериалам вообще ничего не находит.

**Comment by Jenstel** [comment]
Актуально на последней версии плагина?
